# Problem #2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# https://projecteuler.net/problem=2

sumOfFibs = 2
firstFib = 1
secondFib = 2
nextFib = 0

while nextFib < 4000000:

    nextFib = firstFib + secondFib

    if nextFib % 2 == 0:
        sumOfFibs += nextFib

    firstFib = secondFib
    secondFib = nextFib

print sumOfFibs
